version = "1"

[package]
name = "test_kira"
version = "0.0.4"
authors = ["Jiaming Meng <jackm@exoad.net>"]
description = "A small test project for Kira"

[workspace]
src = ["./sub/test.kira"]
entry = "./sub/test.kira"

[build]
outDir = "build"
target = "none"
debug = false
emitIR = "dump_symbols.kira.txt"

[dependencies.kira_lib]
path = "kira"

